#!/usr/bin/env bash
#
# Example config file for cdm(1).
# Values set here is the default as in cdm(1).

# List of programs, commands with whitespaces should be quoted or escaped.
# If unset, all sessions in /usr/share/wayland-sessions, /etc/X11/Sessions
# or /usr/share/xsessions are offered as choices.
#
# (An example:)
#binlist=(
#   '/usr/bin/sway'                      # Launch your Sway session,
#   '/bin/bash --login'                  # or just execute your shell,
#   '/usr/bin/xonsh -l -i'               # or launch another shell,
#   '/usr/bin/fbterm'                    # or start a frame buffer console,
#   '/usr/bin/shutdown -r now'           # or reboot,
#   '/usr/bin/shutdown now'              # or shutdown,
#   '/usr/bin/cdm ~/.config/cdm/submenu' # or go to a submenu :)
#)

# List all program display names, one-by-one matched with $binlist.
# Names with whitespaces should be quoted or escaped.
#
# (Continued example:)
#namelist=('Sway session' bash xonsh fbterm reboot shutdown submenu)

# Type of the programs, one-by-one matched with $binlist.
# `C' for *C*onsole programs, which would be `exec'ed.
# `W' for *W*ayland programs, which would be `exec'ed as well.
# `X' for *X* programs, which would be run with cdm-xlaunch(1).
#
# (Continued example:)
#flaglist=(W C C C C C C)

# Style for the cdm dialog, which is printed with dialog(1).
# Default to unset, causing dialog(1) to use the system wide default.
# See /usr/share/doc/cdm/themes for some nice choices.
dialogrc=/usr/share/doc/cdm/themes/cdm
#dialogrc=/home/$USER/.config/cdm/themes/miromiro

# Index of the first item in the menu.
countfrom=0

# Set default display.
display=0

# Should cdm(1) stick to the specified display?
locktty=no

# Additional arguments to pass to X server, which is usually called as:
#   /usr/bin/X :$display "${serverargs[@]}" vt$((xtty+display))
# Arguments with whitespaces should be quoted or escaped.
serverargs=(-keeptty -nolisten tcp)
